### ISSUE TITLE
Design and implimentation ideas

### ISSUE THREAD

**Issue by nuke-web3** [NukeManDan/crypto_cookie_jar#1]
I would love to get some input of what folks want to see done with a website for 
- [ ]  Welcome page
- [ ]  Check-in to meeting / scan EventBrite tickets 
- [ ]  Launchpass / slack invite
- [ ]  Scan a QR to donate crypto to group wallet
- [ ]  Wallet recommendations and/or email suggested places to start via QR 
- [ ]  Integrate a fiat method of payment. (?)
- [ ]  Basic/101 pages with QR codes to direct folks to outside media
- [ ]  Expand into a more public site as a pitch to get folks to attend/learn more
- [ ]  Advertise some of the awesome stuff the people in the group are doing/bios for those interested in side hustles spawn from the group?

Implementation 
- [ ] put this on a tablet w/ a camera that is avalible during the meetup w/ this hosted site

**Comment by Treee** [comment]
I would recommend starting with the easiest first then move to the stuff that will take more time.
QR codes are pretty simple to work with so I would start with that.
There are great 101 websites that we can point to so we don't have to generate that content ourselves.

**Comment by nuke-web3** [comment]
Agreed on 101 info - simply a listing of links (embedded with QR too?) for the basics (youtube / medium / news sites)

**Comment by nuke-web3** [comment]
I would think a responsive design would be best - especially if we go public over just a tablet @ the meetup. do you have a framework suggestion? I would like to either make one or use a very basic framework... https://www.w3schools.com/w3css/4/w3.css might fit the bill to start?

I like it because it claims to be:
>Smaller and faster than any other CSS frameworks.
Easier to learn, and easier to use than any other CSS frameworks.
Better cross-browser compatibility than any other CSS frameworks.
Uses standard CSS only (No jQuery or JavaScript library).
Supports modern responsive mobile first design by default.
Provides CSS equality for all browsers: Chrome, Firefox, Edge, IE, Safari, Opera, ...
Provides CSS equality for all devices: desktop, laptop, tablet, and mobile.
Speeds up and simplifies web development:

Otherwise - a step up could be bootstrap. Worth learning? https://www.w3schools.com/bootstrap/default.asp

**Comment by NukeManDan** [comment]
I would like to solicit for design ideas to jump from in terms of a site layout/look&feel... any thoughts?

**Comment by Treee** [comment]
I would recommend using either
React: https://reactjs.org/ (Lower skill curve)
or 
https://angular.io/ (Higher skill curve, used in industry more)

**Comment by nuke-web3** [comment]
Thanks @Treee . Thinking about it a bit more - as a donation / welcome /checkin and ticket acceptance page on a tablet - I am thinking about non-scrolling more app like page interaction.  Also to be lightweight - might actually just build from the ground up in pure HTML5 /CSS/JS ...

**Comment by nuke-web3** [comment]
Color palette ideas from https://www.canva.com/learn/website-color-schemes/ :
***
![image](https://www.canva.com/learn/wp-content/uploads/2016/01/Palette_11-tb-728x0.jpg)
***
![image](https://www.canva.com/learn/wp-content/uploads/2016/01/Palette_16-tb-728x0.jpg)
***
![image](https://www.canva.com/learn/wp-content/uploads/2016/01/Palette_43-tb-728x0.jpg)
***

**Comment by magician11** [comment]
My personal preferences: ReactJS is great if we are going to have any dynamic content. For getting going on design, I quite like Bootstrap, but have been using https://material-ui-next.com/ more recently.

I'm happy to code up the core of what we want.... it's just not clear to me what that is yet.

**Comment by nuke-web3** [comment]
Thanks @magician11 looks like ReactJS is the ticket - I mostly wanted to try and do a group build and avoid the facebook tech (although I shouldn't worry about OSS even from the big guys, eh? )

**Comment by magician11** [comment]
I hear you on avoiding Facebook tech @NukeManDan . As a company the association is not good. I don't use Facebook itself anymore. But ReactJS itself is great.

I've heard good things about https://vuejs.org/ which I'm happy to explore. I have used https://angularjs.org/ but didn't really like it.. and it's part of another big company.. Google.

Actually I've heard really good things about https://preactjs.com/ and would be most keen to try this as an alternative to React.

Also, for an initial simple page, we may not need any JS framework. We could literally code something in pure CSS and HTML, and add JS as needed. It depends how much dynamic content the page has.

Using something like [Bootstrap](https://getbootstrap.com/) or [Materialize](http://materializecss.com/) help because I'm not a designer and so we get some pretty good looking components straight away.

**Comment by nuke-web3** [comment]
Yeah - all good points. I think that it can start very minimalistic and - for me to learn - raw HTML/CSS/JS was my thought. Vue or Preact sound interesting if we are doing something heavier.

**Comment by magician11** [comment]
Ok great. Not a bad way to learn either... 

Just need a design now as to what you want to build.. and we can start coding it up from scratch 😀

**Comment by nuke-web3** [comment]
So I think 4fd0fc43af6680f2453ad7a426b9593ba9acef83 got at one key feature - no-scroll

I want to have a single page interface aimed at use on a tablet (and maybe cell) that is out during the meetup with a page for:
* Welcome / splash home screen w/ logo
* (possible) checking into the meetup via eventbrite integration (and/or roll our own?)
* resource for learning links/resources for 101 types
* join the slack channel
* making donations via BTC QR and (possibly) other wallets/shapeshift and link for 101 wallet info
* (possible) email entry for basic crypto resources / info about how to join slack.

It would be nice to have fade in/out transitions between pages - and I know that HTML5/CSS even on it's own can make that happen. Might just need some basic JS to do email - so maybe target that last if at all. As for Eventbrite - could link to main site/app or remove that - just have someone with a phone to check in on app. So a page w/ a reminder

**Comment by nuke-web3** [comment]
I figure that a single page that has transitions on click/touch could work w/ fade in&out ... but would it be easier/better/possible to have individual files for each?

**Comment by magician11** [comment]
I don't know if we really need multiple pages for this?

Why no scroll? Given there will be different devices with different screen sizes, we just won't fit everything on one page... maybe I need to see some sketches to see what you have in mind?
